### PR TITLE
Add column metadata build option

### PR DESCRIPTION
**Pull request by jschueller**
It is incompatible with SQLITE_OMIT_DECLTYPE, so the latter should have its own option too.

### CODE REVIEW

**Comment by azadkuh** [comment]
@jschueller 
thank you so much for this PR. I just re-aligned and sorted the items to help my OCD and pushed your commit in `dev` branch.
please check if it is alright I will also move the master.

**Comment by azadkuh** [comment]
@jschueller
please also check the [next](https://github.com/azadkuh/sqlite-amalgamation/commit/8010e589d69bb722815f83a443f1ec379d65f7b3) commit as I believe we can automate these two options.

**Comment by jschueller** [comment]
maybe its simpler to leave them independent, maybe one could want to disable both

**Comment by azadkuh** [comment]
hmm, that makes sense. but we shouldn't allow compiling with both options enabled, shall we?

**Comment by jschueller** [comment]
yes, that's good for me

**Comment by azadkuh** [comment]
cherry-picked and merged

**Pull request closed without merging**
